### ISSUE TITLE
 Code Optimization for Improved Performance and Best Practices

### ISSUE THREAD

**Issue by WoodMMK** [WoodMMK/EGCO213-p2#1]
Everything works fine now 🎉, After fixing some parcel calculation bug. But implementation in some class can be optimized for improved adherence to best practice.

## some key point that needs improvement
1. Thread synchronization
- right now, we are using try-catch block every time we use barrier.await() which might slow down the app.

2. Code Duplication: 
- Some class may already has get() method that can be used to access private member. 
- Some logic at parcel calculation might not be optimal. maybe the variables are used

## Task list
- [ ] modify barrier.await()'s try catch block. maybe into a single try-catch block
- [ ] optimize parcel calculation
- [ ] recheck if we are accessing variable without using already implemented method

Thanks!

**Comment by CirCleMan7** [comment]
I'm just fixing a calculation part of the code in DeliveryShop, but I'm not sure if it's correct. Can you check my branch and review it for me? I also rearranged some header methods to make them easier to find.
